export {default as NavBar} from './NavBar'
export {default as Footer} from './Footer'
export {default as Gallery} from './Carousel'
export {default as Country} from './Country'
export {default as CardCar} from './CardCar'
export {default as CardDetails} from './CardDetails'
export {default as ReviewCard} from './ReviewCard'
export {default as SearchBar} from './SearchBar'
export {default as TrashCar} from './TrashCar'
export {default as CardRanking} from './CardRanking'
export {default as CardUserReviews} from './CardUserReviews'
export {default as RatingUserReviews} from './RatingUserReviews'
export {default as SideBar} from './SideBar'

