export {default as HomePage} from './HomePage'
export {default as Login} from './Login'
export {default as ProfileInfo} from './ProfileInfo'
export {default as Review} from './Review'
export {default as Register} from './Register'
export {default as DetailsNvidia} from './DetailsNvidia'
export {default as Detailsintelcore} from './Detailsintelcore'
export {default as DetailsKeyboard} from './DetailsKeyboard'