export default[{
    id: "1",
    imgsrc : "img/Nvidia.jpg",
    title: "NVIDIA GEFORCE RTX 3070 8GB (VR READY)",
    price: "Precio: $679",
    titledetail1: "CHIPSET MANUFACTURER",
    detail1: "NVIDIA",
    titledetail2: "GPU",
    detail2: "Geforce RTX 3070",
    titledetail3: "CORE CLOCK",
    detail3: "1530 MHz",
    titledetail4: "BOOST CLOCK",
    detail4: "OC Mode: 1800 Mhz Gaming Mode (Default) 1770 MHz",
    titledetail5: "CUDA CORES",
    detail5: "1280",

    
},
{
    id: "2",
    imgsrc : "img/intelcore.jpg",
    title: "INTEL CORE I7-12700F 12-CORE",
    price: "Precio: $359",
    titledetail1: "PROCESSOR NUMBER",
    detail1: "i7-12700F",
    titledetail2: "NUMBER OF CORES",
    detail2: "12",
    titledetail3: "MAXIMUN TURBO FREQUENCY",
    detail3: "4,90 GHz",
    titledetail4: "MAXIUM MEMORY SIZE",
    detail4: "128 GB",
    titledetail5: "CACHE",
    detail5: "25 MB Intel® Smart Cache",
   
},
{
    id: "3",
    imgsrc : "img/keyboard.jpg",
    title: "KEYBOARD AND MOUSE RAZER",
    price: "Precio: $39",
    titledetail1: "MODEL KEYBOARD",
    detail1: "Cynosa Chroma Lite",
    titledetail2: "KEYBOARD BACKLIGHT COLOR",
    detail2: "Green",
    titledetail3: "MODEL MOUSE",
    detail3: "Abyssus Lite",
    titledetail4: "MOUSE SENSOR RESOLUTION",
    detail4: "6400 dpi",
    titledetail5: "MOUSE COLOR",
    detail5: "Green",
}
]

